feat: Add a per group toggle for autobalance
azerothcore/mod-autobalance pull request #66
Opened 2020-05-09 00:17 UTC by hauspie

This pull request adds commands for a player to enable or disable the autobalance system on a per group basis.

Dungeon and raids autobalance will now be enabled or disabled based on the configuration of the party leader. This allows player to choose either they want autobalance or not (kind of similar to the normal/heroic mode choice)

This functionnality can be enabled or disabled in the config file so that if you want your server to force autobalance for everyone, you still can.

2021-05-05 09:29 UTC, Winfidonarleyan commented on src/AutoBalance.cpp
> +    if (NULL != group)
```cpp
if (group)
```

2021-05-05 10:24 UTC, Helias commented on src/AutoBalance.cpp
> +    if (NULL != group)
same for `if (NULL != leader)` I guess

2021-06-26 17:41 UTC, Yehonal requested changes
This is an interesting feature @hauspie can you complete this with our suggestions?

2021-06-26 17:41 UTC, Yehonal commented on src/AutoBalance.cpp
> +    static bool SetABAutobalance(ChatHandler *handler, bool enable)
Maybe this should be named something like:

```suggestion
    static bool SetGroupAutobalance(ChatHandler *handler, bool enable)
```

2023-06-17 23:59 UTC, pangolp commented
Greetings. What is the current status of this pull request? I ask, because the idea is to try to keep the repository as updated as possible, and I see that it was created in 2020, and has not had recent messages. In addition, it has some conflicts. In any case, you can close and take the code, with the respective credits and create a new application. I am waiting for a confirmation message. Thank you.

2023-06-29 15:44 UTC, closed without merging